env:
  es2021: true
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-restricted-syntax: ['off', 'ForOfStatement']
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  operator-linebreak: ['error', 'after']
  implicit-arrow-linebreak: ['off']
